openapi: 3.1.0
x-stoplight:
  id: me8l2h1u3ej92
info:
  title: 20refs
  version: '1.0'
  description: |-
    > #### Danger Will Robinson!
    >
    > Here is a danger callout!****  
    > here is more text to demonstration something happening to the callout boxes ability to wrap text in Firefox but not Chrome or Safari (who uses Safari)  
    >  
    > ```code code code code code the word code has lost all meaning isn't that weird i bet there's a german word for when that happens```
  summary: sdfs sddsd
servers:
  - url: 'http://localhost:3000'
paths:
  '/users/{userId}':
    parameters:
      - schema:
          type: integer
        name: userId
        in: path
        required: true
        description: Id of an existing user.
  /user:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: 'stoplight://resources/overrides/GJPOBbTBaV8'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '302':
          description: Found
          content:
            application/json:
              schema:
                $ref: 'stoplight://resources/overrides/GJPOBbTBaV8'
        '400':
          description: Missing Required Information
          content:
            application/json:
              schema:
                $ref: 'stoplight://resources/overrides/GJPOBbTBaV8'
        '409':
          description: Email Already Taken
          content:
            application/json:
              schema:
                $ref: 'stoplight://resources/overrides/GJPOBbTBaV8'
        1XX:
          description: Informational
          content:
            application/json:
              schema:
                $ref: 'stoplight://resources/overrides/GJPOBbTBaV8'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                dateOfBirth:
                  type: string
                  format: date
              required:
                - firstName
                - lastName
                - email
                - dateOfBirth
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: 'Create a new user. [link](xids_copy.yaml/paths/~1users~1{userId}/patch)'
      x-stoplight:
        id: ouytbjljvjl9h
  /four: {}
components:
  schemas:
    User:
      $ref: 'stoplight://resources/overrides/1QkT7j1bAWc'
      x-stoplight:
        id: n0eudv09fwioz
  parameters:
    test:
      name: test
      in: query
      required: false
      schema:
        type: string
    test2:
      name: test2
      in: query
      required: false
      schema:
        type: string
    test3:
      name: test3
      in: query
      required: false
      schema:
        type: string
