openapi: 3.1.0
x-stoplight:
  id: kglk24k4d4vi9
info:
  title: ClickMe
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /wtf:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-wtf
      x-stoplight:
        id: 28amx3vy3eb4w
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'stoplight://resources/overrides/AZ0Y5f8nqLc'
      description: ''
    put:
      summary: Your PUT endpoint
      tags: []
      responses: {}
      operationId: put-wtf
      x-stoplight:
        id: 28amx3vy3eb4w
  /test:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-test
      x-stoplight:
        id: 28amx3vy3eb4w
webhooks:
  PricePulseTrigger:
    post:
      description: 'A competitors price cache has changed, event'
      requestBody:
        description: >-
          Context of the cache key (product key) and the list of changes
          detected
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompetitorRateEvent'
      responses:
        '200':
          description: >-
            Return a 200 status to indicate that the data was received
            successfully
        '500':
          description: Return a 500 status
components:
  schemas:
    User:
      $ref: 'stoplight://resources/overrides/AZ0Y5f8nqLc'
      x-stoplight:
        id: 28amx3vy3eb4w
