openapi: 3.1.0
x-stoplight:
  id: kglk24k4d4vi9
info:
  title: ClickMe
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /wtf:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-wtf
      x-stoplight:
        id: 28amx3vy3eb4w
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'stoplight://resources/overrides/AZ0Y5f8nqLc'
      description: ''
    put:
      summary: Your PUT endpoint
      tags: []
      responses: {}
      operationId: put-wtf
      x-stoplight:
        id: 28amx3vy3eb4w
  /test:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-test
      x-stoplight:
        id: 28amx3vy3eb4w
components:
  schemas:
    User:
      $ref: 'stoplight://resources/overrides/AZ0Y5f8nqLc'
      x-stoplight:
        id: 28amx3vy3eb4w
