openapi: 3.1.0
x-stoplight:
  id: 163bw44l3add9
info:
  title: xids
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/users/{userId}':
    parameters:
      - schema:
          type: integer
        name: userId
        in: path
        required: true
        description: Id of an existing user.
    patch:
      summary: ClickMe
      x-stoplight:
        id: 3mvuis7k66vha
      operationId: patch-users-userId
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User Not Found
        '409':
          description: Email Already Taken
      description: Update the information of an existing user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: object
                  properties:
                    test1:
                      type: string
                      x-stoplight:
                        id: kvah9tq58k1ev
                lastName:
                  type: string
                email:
                  type: string
                  description: 'If a new email is given, the user''s email verified property will be set to false.'
                dateOfBirth:
                  type: string
                test:
                  type: object
                  x-stoplight:
                    id: dy21d1lgoidac
                  properties:
                    test2:
                      type: string
                      x-stoplight:
                        id: ied5lwyy4hrqe
            examples:
              Update First Name:
                value:
                  firstName: Rebecca
              Update Email:
                value:
                  email: rebecca@gmail.com
              Update Last Name & Date of Birth:
                value:
                  lastName: Baker
                  dateOfBirth: '1985-10-02'
        description: Patch user properties to update.
  /user: {}
components:
  schemas:
    User:
      title: User
      x-stoplight:
        id: ack4vzeaxu9mx
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
          x-stoplight:
            id: awyfrk9x8xmqf
        firstName:
          type: string
          x-stoplight:
            id: 6m2c23ki08s9a
        lastName:
          type: string
          x-stoplight:
            id: m3xd5q3btkb0x
        email:
          type: string
          format: email
          x-stoplight:
            id: uhlt65bk463ra
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
          x-stoplight:
            id: 6l2haseh93smi
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
          x-stoplight:
            id: f1v704ym4vo40
        createDate:
          type: string
          format: date
          description: The date that the user was created.
          x-stoplight:
            id: hutop5lgq6t2h
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
